on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'printing folder content(before)'
        run: ls

      - uses: actions/checkout@v3 

      - name: 'doker login'
        run: docker login --username mohamed203 --password dckr_pat_Q_OVMVMKNAdGpC9t2UsWzlqh9ng    
